services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build:
      context: ../organic-webserver/organic-webserver
      dockerfile: ../../organic-deploy/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=5432
      - ORGANIC_SECRET_KEY=$ORGANIC_SECRET_KEY
      - ORGANIC_SERVER_NAME=$ORGANIC_SERVER_NAME

volumes:
  db:
